#!/usr/bin/env bash

prompt_ascii=(
"      ███╗   ██╗███████╗██╗  ██╗██╗   ██╗███████╗      "
"      ████╗  ██║██╔════╝╚██╗██╔╝██║   ██║██╔════╝      "
"      ██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║███████╗      "
"      ██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║╚════██║      "
"      ██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝███████║      "
"      ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝      "
)

ofetch_config() {
    cat << 'EOF'
 ASI[0]="38;2;59;130;246"
title=("openNebula Linux")
sep="  "
key_color=("38;2;59;130;246")
a_title=("1")
bold=("on")
LsColors=("fi=0")
EOF
}
